### ISSUE TITLE
Bug in config/triggers.py

### ISSUE THREAD

**Issue by aalvesan** [uhh-cms/hh2bbtautau#7]
For e tauh there are 2 triggers with different id but the same name (which should be unique). The same happens for mu tauh.

**Comment by riga** [comment]
Thanks for opening this!

For future reference: https://github.com/uhh-cms/hh2bbtautau/blob/master/hbt/config/triggers.py#L101-L148

**Comment by riga** [comment]
I checked the available triggers again.

There are no (tau) HPS triggers in 2017, but they do exist in 2018, so we have to pay attention there. However, the previous code (before the fix in https://github.com/uhh-cms/hh2bbtautau/commit/96e12e6d6f1b4073ff4132b6cdd1c3106abbfeed) shows how to make triggers data / mc dependent so the solution will be very similar.

Needless to say, I removed any sign of HPS triggers in the 2017 trigger config in the aforementioned commit.
