### ISSUE TITLE
Problem concatenating awkward arrays

### ISSUE THREAD

**Issue by aalvesan** [uhh-cms/hh2bbtautau#8]
When trying to run a background sample, the following code throws an error
https://github.com/uhh-cms/hh2bbtautau/blob/25d4fb437586d34a633d3dc44dd9598c2808c139/hbt/production/hhbtag.py#L80-L88
`ValueError: cannot convert to RegularArray because subarray lengths are not regular`

**Comment by riga** [comment]
Hi!

So, `f[where]` is empty in these cases?

Do you have a full command to reproduce this?

**Comment by riga** [comment]
Turns out, this still works in awkward 2.2.2, but fails in the newer 2.2.4 version.

These implicit changes of core behavior between patch versions are really suboptimal to put it mildly.
